### ISSUE TITLE
Need to better aligne profile picture with username/email

### ISSUE THREAD

**Issue by jerryleungwh** [brndnng/teamform-seed#24]

**Comment by brndnng** [comment]
![sketch](https://cloud.githubusercontent.com/assets/21734054/20034995/11f63154-a40e-11e6-9d03-f4c12c0109c9.png)
profile picture will overlap with username/email box

**Comment by brndnng** [comment]
can try to add padding for img element and the textbox element

**Comment by jerryleungwh** [comment]
Fixed. No problem found in any view mode at the moment.
